project:
  type: website

website:
  title: "Blogsite"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Solab5 
      - icon: twitter
        href: https://twitteer.com/aboutScience 
    left:
      - href: Publication.qmd 
        text: Publication
format:
  html:
    theme: cosmo
    css: styles.css



